#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 28 14:48:32 KST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto e87a57d0c9c5475fb3147e023fa7a7d7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot andGateSimulation_behav xil_defaultlib.andGateSimulation xil_defaultlib.glbl -log elaborate.log"
xelab -wto e87a57d0c9c5475fb3147e023fa7a7d7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot andGateSimulation_behav xil_defaultlib.andGateSimulation xil_defaultlib.glbl -log elaborate.log

